name: Lib Test

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up stack and run tests
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        run: docker-compose up -d
      
      
      

