name: Lib Test

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      API_ADDR: "http://localhost:8080"
    steps:
    - uses: actions/checkout@v2
    - name: Set up stack
      run: docker-compose up -d postgresql vault accountapi
    - name: Check running containers
      run: docker ps -a
    - name: tests
      run: go test - v ./... --cover
      
      
      
      
      
      

